title: "Diribéo"
description: "Le néguentrope"
url: "http://www.diribeo.fr"
image: "/images/favicons/media.png"
baseurl: ""
plugins:
  - jekyll-feed
collections:
  posts:
    output: true
    permalink: /actualites/:title
  clients:
    output: true
    permalink: /clients/:title
  equipe:
    output: false
    permalink: /equipe/:title
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "article"
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "client"
